/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadaragama
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
        setExtendedState(Home.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cusmanage = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_carmanage = new javax.swing.JButton();
        btn_rent = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();
        btn_usermanage = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setMaximumSize(new java.awt.Dimension(1366, 728));
        setMinimumSize(new java.awt.Dimension(1366, 728));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cusmanage.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_cusmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managecus.png"))); // NOI18N
        btn_cusmanage.setText("Customer Manage");
        btn_cusmanage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_cusmanage.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_cusmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cusmanageActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cusmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 70));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        btn_carmanage.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_carmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managecar.png"))); // NOI18N
        btn_carmanage.setText("Car Manage");
        btn_carmanage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_carmanage.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_carmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carmanageActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 70));

        btn_rent.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_rent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rentmanage.png"))); // NOI18N
        btn_rent.setText("Rent Car");
        btn_rent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_rent.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 220, 60));

        btn_return.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/returnmanage.png"))); // NOI18N
        btn_return.setText("Return Car");
        btn_return.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_return.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 220, -1));

        btn_usermanage.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_usermanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manageuser.png"))); // NOI18N
        btn_usermanage.setText("User Manage");
        btn_usermanage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_usermanage.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_usermanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usermanageActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usermanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, -1));

        btn_reports.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports.png"))); // NOI18N
        btn_reports.setText("Reports");
        btn_reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_reports.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 220, -1));

        btn_logout.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btn_logout.setText("Log Out");
        btn_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_logout.setPreferredSize(new java.awt.Dimension(240, 59));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 220, -1));

        lbl_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wall3.jpg"))); // NOI18N
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1370, 800));

        setSize(new java.awt.Dimension(1369, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Do you want to Close the Application?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
           System.exit(0);
       } 
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_cusmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cusmanageActionPerformed
        CustomerManage cusm = new CustomerManage(this,true);
        cusm.setVisible(true);
                
        
    }//GEN-LAST:event_btn_cusmanageActionPerformed

    private void btn_carmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carmanageActionPerformed
     
        CarManage cm = new CarManage(this,true);
        cm.setVisible(true);
    }//GEN-LAST:event_btn_carmanageActionPerformed

    private void btn_rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rentActionPerformed
        Rent r1 = new Rent(this,true);
        r1.setVisible(true);
    }//GEN-LAST:event_btn_rentActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        Returned r2 = new Returned(this,true);
        r2.setVisible(true);
    }//GEN-LAST:event_btn_returnActionPerformed

    private void btn_usermanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usermanageActionPerformed
        UserManage u = new UserManage(this,true);
        u.setVisible(true);
    }//GEN-LAST:event_btn_usermanageActionPerformed

    private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
        
        new Reports().setVisible(true);
    }//GEN-LAST:event_btn_reportsActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        
        int a=JOptionPane.showConfirmDialog(null,"Do you want to Log Out?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
           this.setVisible(false);
        new Login().setVisible(true);
       }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_carmanage;
    private javax.swing.JButton btn_cusmanage;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_rent;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_usermanage;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
