/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ManageLoging;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadaragama
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_close = new javax.swing.JButton();
        txt_uname = new javax.swing.JTextField();
        txt_upw = new javax.swing.JPasswordField();
        btn_loging = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_forgotpw = new javax.swing.JLabel();
        btn_signup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_loging_title = new javax.swing.JLabel();
        lbl_carlogo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(173, 170, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        lbl_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_closeActionPerformed(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 30, 30));

        txt_uname.setBackground(new java.awt.Color(173, 170, 168));
        txt_uname.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_uname.setText("UserName");
        txt_uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 159, 186)));
        txt_uname.setCaretColor(new java.awt.Color(153, 153, 153));
        txt_uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_unameMouseEntered(evt);
            }
        });
        jPanel2.add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));

        txt_upw.setBackground(new java.awt.Color(173, 170, 168));
        txt_upw.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_upw.setText("Password");
        txt_upw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 159, 186)));
        jPanel2.add(txt_upw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, -1));

        btn_loging.setBackground(new java.awt.Color(173, 170, 168));
        btn_loging.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_loging.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cl.png"))); // NOI18N
        btn_loging.setText("Sign In");
        btn_loging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logingActionPerformed(evt);
            }
        });
        jPanel2.add(btn_loging, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btn_clear.setBackground(new java.awt.Color(173, 170, 168));
        btn_clear.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        lbl_forgotpw.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        lbl_forgotpw.setText("Forgot Password?");
        lbl_forgotpw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_forgotpwMouseMoved(evt);
            }
        });
        lbl_forgotpw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgotpwMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_forgotpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, -1));

        btn_signup.setBackground(new java.awt.Color(173, 170, 168));
        btn_signup.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_signup.setText("Sign up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jPanel3.setBackground(new java.awt.Color(6, 159, 186));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_loging_title.setBackground(new java.awt.Color(247, 58, 30));
        lbl_loging_title.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lbl_loging_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_loging_title.setText("..Sign In..");

        lbl_carlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car.png"))); // NOI18N

        lbl_title.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lbl_title.setText("Car Rental Service");

        lbl_1.setText("Developed By");

        lbl_2.setBackground(new java.awt.Color(0, 0, 153));
        lbl_2.setForeground(new java.awt.Color(0, 0, 153));
        lbl_2.setText("@Harith_Hadaragama");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbl_loging_title, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbl_loging_title, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_1)
                    .addComponent(lbl_2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(723, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_closeActionPerformed
       int a=JOptionPane.showConfirmDialog(null,"Do you want to Close the Application?","Select",JOptionPane.YES_NO_OPTION);
       if(a==0){
           System.exit(0);
       } 
    }//GEN-LAST:event_lbl_closeActionPerformed

    private void btn_logingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logingActionPerformed
        this.setVisible(false);
        ManageLoging mc = new ManageLoging();
        mc.setInput(txt_uname.getText(),txt_upw.getText());
        mc.validateForm();
    }//GEN-LAST:event_btn_logingActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       txt_uname.setText("");
       txt_upw.setText("");
       
    }//GEN-LAST:event_btn_clearActionPerformed

    private void lbl_forgotpwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotpwMouseClicked
        setVisible(false);
        new ForgotPassword().setVisible(true);
        
    }//GEN-LAST:event_lbl_forgotpwMouseClicked

    private void lbl_forgotpwMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotpwMouseMoved
        lbl_forgotpw.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbl_forgotpwMouseMoved

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        setVisible(false);
        new UserSignUp().setVisible(true);
        
    }//GEN-LAST:event_btn_signupActionPerformed

    private void txt_unameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_unameMouseEntered
        txt_uname.setText("");
       txt_upw.setText("");
       
    }//GEN-LAST:event_txt_unameMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_loging;
    private javax.swing.JButton btn_signup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_carlogo;
    private javax.swing.JButton lbl_close;
    private javax.swing.JLabel lbl_forgotpw;
    private javax.swing.JLabel lbl_loging_title;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_uname;
    private javax.swing.JPasswordField txt_upw;
    // End of variables declaration//GEN-END:variables
}
