/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ManageUser;

/**
 *
 * @author Hadaragama
 */
public class UserSignUp extends javax.swing.JFrame {

    /**
     * Creates new form UserSignUp
     */
    public UserSignUp() {
        initComponents();
    }
    private void clear(){
       txt_username.setText("");
       txt_email.setText("");
       txt_pw.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_usersignup_title = new javax.swing.JLabel();
        lbl_close = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_pw = new javax.swing.JLabel();
        txt_pw = new javax.swing.JTextField();
        user_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(6, 159, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_usersignup_title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lbl_usersignup_title.setText("User Registration ");
        jPanel1.add(lbl_usersignup_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));

        lbl_close.setBackground(new java.awt.Color(6, 159, 186));
        lbl_close.setForeground(new java.awt.Color(6, 159, 186));
        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        lbl_close.setBorder(null);
        lbl_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_closeActionPerformed(evt);
            }
        });
        jPanel1.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 30));

        jPanel2.setBackground(new java.awt.Color(173, 170, 168));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lbl_username.setText("User Name");
        jPanel2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, -1));

        btn_clear.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        btn_register.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txt_username.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txt_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 158, -1));

        txt_email.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txt_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 158, -1));

        lbl_email.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lbl_email.setText("Email");
        jPanel2.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lbl_pw.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lbl_pw.setText("Password");
        jPanel2.add(lbl_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txt_pw.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txt_pw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 158, -1));

        user_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoUser.png"))); // NOI18N
        jPanel2.add(user_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 100, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        ManageUser u = new ManageUser ();
        u.setInput("", txt_username.getText(),txt_email.getText(),txt_pw.getText());
        u.validateInputForm();
        clear();
        
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void lbl_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_closeActionPerformed
         this.setVisible(false);
         new Login().setVisible(true);
    }//GEN-LAST:event_lbl_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_register;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lbl_close;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_pw;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_usersignup_title;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel user_logo;
    // End of variables declaration//GEN-END:variables
}
